/// Flutter icons Eyes
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Eyes
///      fonts:
///       - asset: fonts/Eyes.ttf
///
///
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class Eyes {
  Eyes._();

  static const _kFontFam = 'Eyes';
  static const String? _kFontPkg = null;

  static const IconData bleeding_eye =
      IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burning_eye =
      IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_monster =
      IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeball =
      IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
